# GitHub Issue Format Guide for Virtual Office Agents
# =============================================================
# This file defines the EXACT markdown structure that agents must output
# when using the [ISSUE_CREATE: Title | Body] trigger.
#
# RULE: The "Body" portion of [ISSUE_CREATE: Title | Body] must follow
# one of the three templates below based on the issue type.
# Agents should SELECT the correct template based on context.
# =============================================================

# ──────────────────────────────────────────────
# TEMPLATE 1: BUG REPORT
# Use when: reporting a broken behaviour, regression, or unexpected error.
# ──────────────────────────────────────────────

BUG_REPORT_TEMPLATE = """
**Reported by:** {AGENT_NAME} ({AGENT_ROLE})
**Date:** {DATE}

## 🐛 What's broken?
{WHAT_IS_BROKEN}

## 📍 Where does it happen?
- **Environment:** {ENVIRONMENT}
- **Component:** {COMPONENT}

## 🔁 Steps to Reproduce
{STEPS_TO_REPRODUCE}

## ✅ Expected behaviour
{EXPECTED}

## ❌ Actual behaviour
{ACTUAL}

## 🧮 Impact
- **Severity:** {SEVERITY}
- **Blocking release?** {BLOCKING}

> 🤖 Auto-generated by Virtual Office agent — review before assigning.
"""

# USAGE EXAMPLE (in agent output):
# [ISSUE_CREATE: Login page crashes on mobile | **Reported by:** Aiden (Tech Lead)
# **Date:** 2026-05-31
#
# ## 🐛 What's broken?
# The login page throws a JS runtime error on Safari iOS 17 when the user taps "Sign In".
# ...
# ]


# ──────────────────────────────────────────────
# TEMPLATE 2: FEATURE REQUEST
# Use when: proposing a new product feature or improvement.
# ──────────────────────────────────────────────

FEATURE_REQUEST_TEMPLATE = """
**Raised by:** {AGENT_NAME} ({AGENT_ROLE})
**Date:** {DATE}

## ✨ What do we want to build?
{FEATURE_SUMMARY}

## 🎯 Why does this matter?
{BUSINESS_CASE}

## 👤 Who's it for?
- **Primary user:** {TARGET_USER}
- **Estimated reach:** {REACH}

## 📐 Acceptance Criteria
{ACCEPTANCE_CRITERIA}

## 📅 Priority / Sprint
- **Suggested priority:** {PRIORITY}
- **Target sprint:** {SPRINT}

> 🤖 Auto-generated by Virtual Office agent — Liam to review and slot into sprint.
"""


# ──────────────────────────────────────────────
# TEMPLATE 3: SPRINT TASK
# Use when: breaking down work into a concrete, actionable ticket.
# ──────────────────────────────────────────────

SPRINT_TASK_TEMPLATE = """
**Created by:** {AGENT_NAME} ({AGENT_ROLE})
**Date:** {DATE}

## 📋 Task Summary
{TASK_SUMMARY}

## 🎯 Goal
{GOAL}

## ✅ Definition of Done
{DEFINITION_OF_DONE}

## 🧱 Technical Notes
{TECH_NOTES}

## ⏱️ Estimate
- **Story points:** {STORY_POINTS}
- **Sprint:** {SPRINT}

> 🤖 Auto-generated by Virtual Office agent — review DoD before starting.
"""


# ──────────────────────────────────────────────
# AGENT RULES FOR ISSUE CREATION
# ──────────────────────────────────────────────
#
# 1. ALWAYS pick the correct template type. Don't use FEATURE for a BUG.
# 2. Fill in ALL placeholder fields. Never leave {PLACEHOLDER} in the output.
# 3. Keep the title (first arg of ISSUE_CREATE) short: max 60 chars, no brackets.
# 4. Use plain markdown — no HTML tags, no excessive emoji spam.
# 5. End the body with the standard "🤖 Auto-generated" footer.
# 6. Labels are NOT set via the body — queue_manager.sh handles labels via CLI.
#
# WHO CREATES WHAT:
#   - Aiden (Tech Lead)  → Bug reports, sprint tasks (tech-heavy)
#   - Liam (PM)          → Feature requests, sprint tasks (planning-heavy)
#   - Sarah (CEO)        → Feature requests (high-level strategic)
#   - Chloe (Sales/Mkt)  → Feature requests (user-facing / GTM angle)
